### PR TITLE
Add ability to change the background-color of notes

### PR DESCRIPTION
**Pull request by jrfnl**
Also:
- minor layout fix in js file
- updated screenshots
- updated readme file

### CODE REVIEW

**Comment by cdillon** [comment]
Hi Juliette,

I like the note color options.

I need some help with the workflow. I made some minor UI enhancements that I would like you to review. Should I push them as 1.6.1 or 1.7?

Do you have a preferred method/service for minifying JavaScript?

The one thing that I really want to change is the fact that editing an existing note is inside a bordered box while adding a new note is not. I was unable to find a simple way to fix that so I think the HTML structure needs to be changed which of course changes the CSS and JavaScript.

I'm not a fan of the double-click to edit. It doesn't match other WP behavior, the title tooltip can be in the way which forces you to move the mouse, and simply clicking "Edit note" is expected and easy. What do you think about removing the double click?

Chris

**Comment by jrfnl** [comment]
Hi Chris, glad you like the color options ;-)

> I need some help with the workflow.

What I would propose is the following - let me know how this feels to you:

First, we tag the now merged changes to their appropriate versions (1.5 and 1.6), add releases to the GH repo for them and add them to SVN in the WP repo. That way we've dealt with the 'backlog'.

Then (this is a sort of semi-standard workflow for collaboration projects):
- We create a develop branch which is based on the current master.
- We switch the default branch for this repo to the `develop` branch - @mjangda might need to do this, I don't think we can -. This will automatically create new pull requests against `develop` rather than `master`.
- Any changes we're not sure of whether we should make them: create an issue for them which can then be used to gather opinions and discuss the possibilities/possible implications and complications.
- For any changes we want to make, we create a "feature" branch called `feature/short-description` which is based on `develop`. If the feature is a bug fix or response to a feature request with has a GH issue, you would normally add the issue nr to the branch name, like: `feature/123-fix-js-bug`. You work on the feature only in that branch. You can push the feature branch to your own fork or to this repo.
- Once you think something is ready for merging, you create a pull request from the feature branch to `develop` and add the label `reviewmerge`. If you like, you can assign the reviewing to someone. Generally if someone 'from the team' opens a PR and does not add the `reviewmerge` label, the PR is not ready for merge yet, but goes to show what is being worked on.
- The reviewer will look at the code and if necessary run some tests with it and give feedback. Just to be sure: feedback should be feature/code centric and is not meant to be taken personally :sunglasses: 
- Once any needed changes are made (if any), the reviewer will merge the feature. In other words: no-one ever merges their own PRs.
- Depending on the changes in `develop` we decide when it's time to do a release and what the version nr should be. Generally speaking semantic versioning will be used, i.e. fixes to the current features would become 1.6.1, new features introduced: 1.7.0, break in backward compatibility: 2.0.0.
  For a new release, we open a PR with the proposed version nr from `develop` to `master`, merge it, tag the release with the version nr + add release notes to the tag here on GH. We then release to WP SVN.

Also see http://nvie.com/posts/a-successful-git-branching-model/

Current to do's to get this working:
- Release v1.5 and v1.6 to WP SVN. (I've just done the tagging and releasing here on GH)
- Change the default branch to `develop` (I've just created it)

Oh and minor 'oops' - the release dates in the changelog need to be filled in. I'll send in a PR to correct this in a moment and re-tag & re-release 1.6 once that's merged.

> I made some minor UI enhancements that I would like you to review. Should I push them as 1.6.1 or 1.7?

As per the above, I would suggest you create a branch called something like `feature/ui-enhancements`, push it here or to your own fork and open a PR against `develop` labelling it `reviewmerge`. Version nr we can decide upon later.

> Do you have a preferred method/service for minifying JavaScript?

I don't and am open to suggestions. Currently I often use: http://www.minifycss.com/css-compressor/ and http://www.minifyjs.com/javascript-compressor/ if the compression isn't automated via grunt or something.

> The one thing that I really want to change is the fact that editing an existing note is inside a bordered box while adding a new note is not. I was unable to find a simple way to fix that so I think the HTML structure needs to be changed which of course changes the CSS and JavaScript.
> 
> I'm not a fan of the double-click to edit. It doesn't match other WP behavior, the title tooltip can be in the way which forces you to move the mouse, and simply clicking "Edit note" is expected and easy. What do you think about removing the double click?

I'd suggest you open a separate issue to discuss this (as obviously this doesn't really have much to do with this PR). You can copy the relevant bits from the discussion here or reference this discussion in the new issue so other people looking at it know where to find the initial discussion.

Short answer/opinion:
"bordered box": I seem to remember that I also did some work on that for the v2.0 branch. Would have to look to check to see what I did/did not do.
"double-click": I would be careful with changing something like that as it's _removing_ a feature people might have gotten used to.

Hope this helps ;-)

Smile,
Juliette

**Comment by mjangda** [comment]
> We switch the default branch for this repo to the develop branch

Done.

FWIW, most projects that I've worked on that use git-flow have abandoned it after a little while. It tends to be more complicated than the needs of most projects are. <a href="http://scottchacon.com/2011/08/31/github-flow.html">github-flow</a> tends to be more intuitive and feels more natural. Shouldn't discourage you from using it here, but figured I'd share my thoughts :)

**Comment by jrfnl** [comment]
@mjangda Thanks for your quick response. And yeah, opinions vary on git-flow. I generally see it as a good guideline, not as a hard rule-book which must be complied by.
All the same, I've seen a number of projects switch to it and even apply it quite strictly in the WP-sphere as well.

**Comment by cdillon** [comment]
I give up. Please remove me from this project and the wordpress.org repo.

**Comment by jrfnl** [comment]
@cdillon Eh.. it was a suggestion, I'm open to a different approach if that would make you feel more comfortable with it..
Please ping me on skype otherwise (jrf_nl), I'd like to understand why you're leaving.

**Pull request merged**
