### PR TITLE
Feature/version 1.5

### PR DESCRIPTION
**Pull request by jrfnl**
This is version 1.5 from https://github.com/jrfnl/WP-plugin-notes/releases with a few very minor improvements.

All changes are fully documented in the changelog with additional information in the FAQ which has been added to the readme.txt.

The commits are topical for easier code review.
#### Changelog:
- [_Bug fix_] Fixed AJAX delete bug (kept 'waiting').
- [_New feature_] Added output filters for html output (`plugin_notes_row` and `plugin_notes_form`) and the note itself (`plugin_notes_note`).
- [_New feature_] Added ability to use a number of variables in notes which will automagically be replaced - see [FAQ](http://wordpress.org/plugins/plugin-notes/faq/) for more info.
- [_New feature_] Added ability to use markdown syntax in notes - see [FAQ](http://wordpress.org/plugins/plugin-notes/faq/) for more info.
- [_Usability improvement_] Added `<hr />` to allowed tags list and made the tag list filterable through the new `plugin_notes_allowed_tags` filter.
- [_Usability improvement_] Made the default text area for adding a note larger.
- [_Usability improvement_] Added automagical `target="_blank"` to all links in plugin notes including external link indicator.
- [_Usability improvement_] Added contextual help for WP 3.3+,
- [_Usability improvement_] Added FAQ section and plugin license info to the readme file ;-)
- [_Usability improvement_] Added uninstall script for clean uninstall of the plugin.
- [_Usability improvement_] Added minified versions of the js and css files.
- [_I8n_] Created .POT file and added Dutch translation.
- [_Security_] Improved output escaping.

### CODE REVIEW

**Comment by jrfnl** [comment]
P.s.: I got a branch with a PR for 1.6 ready as well once this is merged.

**Comment by cdillon** [comment]
Juliette,

After giving this some thought, I am going to back out and let you take over. You've already done more work than I was planning to do and you should see it through. I have much to learn about plugin development and collaboratove workflows, and I already feel like I'm in the way.

Contact Mo and I'm sure he will grant you admin access to this and the WordPress plugin repo.

Chris

**Comment by jrfnl** [comment]
@cdillon Hi Chris, I respect your view, however, I would be sorry to see you go.
Wouldn't working on this together not be a perfect opportunity to learn about plugin development and collaborative workflows ?
When I originally made the changes which are now in this PR, I hardly knew anything about WP plugin development, so there's bound to be lots which can still be improved or done in a smarter way.

In my experience having more than one person look critically at code will always gain a better result, so I for one, would very much welcome the opportunity to work on this together.

**Comment by cdillon** [comment]
@jrfnl Let's think of the end user. How close is 2.0? Do you see a benefit in releasing 1.5 and 1.6 beforehand? Where are 1.3 and 1.4?

**Comment by jrfnl** [comment]
@cdillon

> How close is 2.0?

Considering I never finished 2.0 and started on it two years ago - no clue how close it is as I'd have to go back to see where I left off. I vaguely remember I stopped while rewriting the js to allow manual ordering for the notes, but not sure now. The short of it is that I was trying to pack too many changes in it.

> Do you see a benefit in releasing 1.5 and 1.6 beforehand?

I'd release 1.5 and 1.6 as they've been out in the wild anyway and users can benefit from already having access to those changes. There is no timeline on when I can finish 2.0

> Where are 1.3 and 1.4?

1.5 could have been called 1.3 (and maybe _should_ have been), but as the 1.5 name/tag is out there I'm hesitant to change that now.

> Let's think of the end user.

Going forward, I think releasing 1.5 and 1.6 would be good.

We could then have a look at 2.0 and see what's been done already and what still needs to be done and possibly what should be left out and maybe left for later releases.

Unfortunately we can't release bits of 2.0 as 1.7 or something as it breaks backward compatibility, hence the 2.0. The reason for that is a change in how dates are saved with notes - now they are saved in formatted form making them impossible to sort or use localization based string formatting. 2.0 changes that and converts all existing dates to usable dates.

So I'd suggest - when I find the time - I'll start sending in bits and pieces of 2.0 which are finished in as PRs. And that we'll look at the open/unfinished points to see what should be in 2.0 and what doesn't need to be to determine when it's release ready.

IMHO useful discussions/critical question like this are good for keeping perspective and are part of the benefits of working on something in a team.

**Comment by cdillon** [comment]
@jrfnl 
OK, I'm onboard. I haven't looked at your PR yet as I'm busy too but I will soon. If 2.0 was close to being ready, I was going to propose we simply move forward with that. But since it's not, let's focus on getting 1.x on track first. If you want, I will create a separate dev branch for version 2.0.

I understand not wanting to disrupt anyone currently using your 1.5. How many do you think there are? Does the readme have the current wordpress.org URI but with "Version: 1.5" so as not to trigger the update message? 

Since we're skipping minor versions, I wonder if it would beneficial to call the next one 1.6 to bring everybody, both current 1.2 users and your 1.5 users, to the same version in one step. If the jump causes any confusion, we only cause it once.

**Comment by jrfnl** [comment]
@cdillon Glad to hear it!

> I haven't looked at your PR yet as I'm busy too but I will soon.

No worries, whenever is a good time for you. Once it's merged, I'll send in the PR for 1.6 which is a lot smaller.

> How many do you think there are?

I haven't got a clue, but my fork has been out there for quite a while and some people have commented in the support forum about using it.

> Does the readme have the current wordpress.org URI but with "Version: 1.5" so as not to trigger the update message? 

Absolutely, I always intended it as give-back/contribution to the original plugin, so we should be fine in that respect.

> Since we're skipping minor versions, I wonder if it would beneficial to call the next one 1.6 to bring everybody, both current 1.2 users and your 1.5 users, to the same version in one step.

We could upload 1.5 and 1.6 in one go to the SVN repo. That way, people will still see the 1.5 release in the history and the changelog, but will only get the upgrade notice for 1.6.

**Comment by jrfnl** [comment]
Oh and yes, once the "finished" branches are merged - I'll add a `develop` branch and will send in the 2.0 PRs to that. (Mo gave me push access too)

**Comment by cdillon** [comment]
Nice work, Juliette.

**Comment by cdillon** [comment]
Let's get your 1.6 merged then I have some thoughts on the UI/UX I would like to discuss.

**Comment by jrfnl** [comment]
Sounds like a plan - I've got the PR for 1.6 waiting in the wings, but am at IPC Berlin until tomorrow evening. Will send the PR once I'm back home/in the office.

Re: UI/UX - I did some work on that for 2.0, so we should have a look at what we can use from that.

**Pull request merged**
